### ISSUE TITLE
Be more selective about which autoCommands get expanded in subscripts

### ISSUE THREAD

**Issue by ctlusto** [desmosinc/mathquill#144]
Basically #129 but with `autoCommands` instead of `autoOperatorNames`.

There is a subset of `autoCommands` that just aren't useful in subscripts and only get in the way of typing other strings. For instance, trying to type `x_{intercept}` will expand the `int` into an integral sign inside the subscript and place your cursor in the lower limit, which is almost certainly not something you'd ever want.

The `autoCommands` that only result in a symbol substitution (`x_{beta}` -> `x_{β}`) are useful. They might be slightly annoying in some situations (`P_{pink}` -> `P_{πink}`), but they're still useful: `alpha beta theta phi pi tau infinity infty`.

The `autoCommands` that "expand" are only annoying (`ans` doesn't expand, but no need to un-italicize it): `sqrt nthroot cbrt sum prod int ans percent`. For these, we should prevent the default behavior inside of simple subscripts.

**Comment by jwmerrill** [comment]
We're hearing that `pi` in particular is a pain when it's treated as an autoCommand in subscripts.

I want to propose that we just don't expand _any_ autoCommands in subscripts.

Downside there is it's not totally crazy to want a subscript of `pi` or `phi` or something like that. Wondering if we could make it so that pasting an autoCommand into a subscript works, but typing it as a sequence of letters does not.

**Comment by jwmerrill** [comment]
This was fixed by https://github.com/desmosinc/mathquill/pull/178
